Interface/Interface/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ged.urls')),
]

Interface/ged/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.liste),
    path('liste', views.liste),
    path('dossiers', views.dossiers),
    path('liste_Ordo', views.tri),
    path('new_dossier', views.new_dossier),
    path('fichier/<dossier>/', views.DossierFichierList),
]

Interface/ged/models.py
from django.db import models


class Dossier(models.Model):
    Nom_Dossier = models.CharField(max_length=50, unique=True)
    Description = models.CharField(max_length=2000)

    def __str__(self):
        return self.Nom_Dossier


class Status(models.Model):
    Status = models.CharField(max_length=20, null=False, blank=False, unique=True)
    Desc_Status = models.CharField(max_length=200, null=False)

    def __str__(self):
        return self.Status


class Fichier(models.Model):
    Nom_Dossier = models.ForeignKey('Dossier', on_delete=models.CASCADE)
    Nom_Fichier = models.CharField(max_length=80, null=False, blank=False, unique=True)
    Date = models.DateField()
    Heure = models.TimeField()
    Origine = models.CharField(max_length=20, default='CDO')
    Objet = models.CharField(max_length=200)
    Fichier = models.FileField(upload_to='.static/Fichiers', null=True, blank=True)
    Version = models.PositiveIntegerField(default=0)
    Status = models.ForeignKey('Status', on_delete=models.PROTECT)
    Observations = models.CharField(max_length=2000, null=True, blank=True)
    Createur = models.CharField(max_length=50, null=False, blank=False)
    Valideur = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.Nom_Fichier


class Commentaires(models.Model):
    Nom_Fichier = models.ForeignKey('Fichier', on_delete=models.CASCADE)
    Comment = models.CharField(max_length=2000, null=True, blank=True)

    def __str__(self):
        return str(self.Nom_Fichier)

Interface/ged/views.py
from django.shortcuts import render, get_object_or_404
from .models import Fichier, Dossier
from django.http import HttpResponse
from django.views.generic import ListView


def index():
    return HttpResponse('Hello Django')


def new_dossier(request):
    return HttpResponse('Hello Django')


# Affichage de la liste des dossiers
def dossiers(request):
    dossier = Dossier.objects.all().order_by('Nom_Dossier')
    return render(request, 'liste_dossier.html', {'dossier':dossier})


# Affichage du contenu du dossier
class DossierFichierList(ListView):
    template_name = 'cont_dossier.html'

    def get_queryset(self):
        self.dossier = get_object_or_404(Dossier, Nom_Dossier=self.kwargs['dossier'])
        return fichier.objects.filter(dossier=self.dossier)


# Affichage brut de la liste des fichiers
def liste(request):
    fichier = Fichier.objects.all()
    return render(request, 'liste_fichier.html', {'fichier': fichier})


# Affichage de la liste des fichiers trié par dossiers
def tri(request):
    fichier = Fichier.objects.all().order_by('Status')
    return render(request, 'liste_fichier.html', {'fichier': fichier})

Interface/templates/Form_Add_Dossier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Interface/templates/cont_dossier.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">

<div>
    <h1>Liste des fichiers</h1>
    <nav>
        <a href="http://localhost:8000/admin" class="btn btn-primary">Administration</a>
        <a href="http://localhost:8000/dossiers" class="btn btn-primary">Dossiers</a>
        <a href="http://localhost:8000/liste_Ordo" class="btn btn-primary">Liste ordonnée</a>
        <a href="http://localhost:8000/new_dossier" class="btn btn-primary">Nouveau Dossier</a>
        <a href="http://localhost:8000" class="btn btn-primary">Retour à l'accueil</a>
    </nav>
    <div>
        <table class="table table-striped">
            <thead class="thead-dark">

            <tr>
                <th scope="col">Nom du Dossier</th>
                <th scope="col">Description</th>

            </tr>
            </thead>
            <tbody>
            {% for dossier in fichier_list %}
            <tr>
<!--

            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

</div>

Interface/templates/liste_dossier.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">

<div>
    <h1>Liste des fichiers</h1>
    <nav>
        <a href="http://localhost:8000/admin" class="btn btn-primary">Administration</a>
        <a href="http://localhost:8000/dossiers" class="btn btn-primary">Dossiers</a>
        <a href="http://localhost:8000/liste_Ordo" class="btn btn-primary">Liste ordonnée</a>
        <a href="http://localhost:8000/new_dossier" class="btn btn-primary">Nouveau Dossier</a>
        <a href="http://localhost:8000" class="btn btn-primary">Retour à l'accueil</a>
    </nav>
    <div>
        <table class="table table-striped">
            <thead class="thead-dark">

            <tr>
                <th scope="col">Nom du Dossier</th>
                <th scope="col">Description</th>

            </tr>
            </thead>
            <tbody>
            {% for x in dossier %}
            <tr>
<!--                <td>{{x.Nom_Fichier}}</td>-->
                <td><a href="http://localhost:8000" class="btn btn-link">{{x.Nom_Dossier}}</a></td>
                <td>{{x.Description}}</td>

            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

</div>

Interface/templates/liste_fichier.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">

<div>
    <h1>Liste des fichiers</h1>
    <nav>
        <a href="http://localhost:8000/admin" class="btn btn-primary">Administration</a>
        <a href="http://localhost:8000/dossiers" class="btn btn-primary">Dossiers</a>
        <a href="http://localhost:8000/liste_Ordo" class="btn btn-primary">Liste ordonnée</a>
        <a href="http://localhost:8000/new_dossier" class="btn btn-primary">Nouveau Dossier</a>
        <a href="http://localhost:8000" class="btn btn-primary">Retour à l'accueil</a>
    </nav>
    <div>
        <table class="table table-striped">
            <thead class="thead-dark">

            <tr>
                <th scope="col">Nom du fichier</th>
                <th scope="col">Dossier</th>
                <th scope="col">Date de dépôt</th>
                <th scope="col">Objet</th>
                <th scope="col">Version</th>
                <th scope="col">Status</th>
            </tr>
            </thead>
            <tbody>
            {% for x in fichier %}
            <tr>
<!--                <td>{{x.Nom_Fichier}}</td>-->
                <td><a href="http://localhost:8000" class="btn btn-link">{{x.Nom_Fichier}}</a></td>
                <td>{{x.Nom_Dossier}}</td>
                <td>{{x.Date}}</td>
                <td>{{x.Objet}}</td>
                <td>{{x.Version}}</td>
                <td>{{x.Status}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

</div>